#!/usr/bin/env Rscript
## Export the data the interactive explorer (docs/index.html) needs.
##
## The explorer is a static page meant for GitHub Pages, so it cannot read the
## CSVs or the yaml at run time through R. This script copies what it needs out
## of the committed outputs and the config into one JavaScript file, so the page
## carries no hand-typed numbers (the project rule is that parameters live in
## analysis/config/sim-params.yaml and results in tables/). Rerun it whenever
## either source changes; analysis/tests/test-tool-engine.mjs checks that the
## exported file still matches tables/sim-quantiles.csv.
##
## Why a .js file rather than .json: a page opened straight from disk
## (file://) is not allowed to fetch() a sibling JSON file in most browsers,
## but it can load a <script src>. Assigning to globalThis keeps it usable
## from Node as well, which is how the test loads it.
##
## Reads:  tables/sim-quantiles.csv, analysis/config/sim-params.yaml
## Writes: docs/cells.js
## Usage:  Rscript analysis/10-export-tool-data.R   (from the project root)

source("analysis/config-helpers.R")

IN  <- "tables/sim-quantiles.csv"
OUT <- "docs/cells.js"
if (!file.exists(IN))
  stop("missing ", IN, ". Run: Rscript analysis/01-simulations.R", call. = FALSE)
if (!requireNamespace("jsonlite", quietly = TRUE))
  stop("package 'jsonlite' is required. Install it with install.packages(\"jsonlite\").",
       call. = FALSE)

cfg <- load_sim_config()
qd  <- read.csv(IN, stringsAsFactors = FALSE)
PS  <- as.integer(cfg_get(cfg, "percentiles"))

## Cells in the config's order, which is the order the menu shows them. Each
## cell's rows are put in percentile order explicitly rather than trusting the
## CSV's row order, because the engine pairs the i-th knot with PS[i].
cell_labels <- vapply(cfg_get(cfg, "cells"), function(x) x$label, character(1))
cells <- lapply(cell_labels, function(lab) {
  z <- qd[qd$cell == lab, ]
  if (nrow(z) == 0) stop("cell '", lab, "' is in the config but not in ", IN, call. = FALSE)
  z <- z[match(PS, z$percentile), ]
  if (anyNA(z$percentile))
    stop("cell '", lab, "' is missing a percentile in ", IN, call. = FALSE)
  ## S is constant within a cell; check rather than take the first row on faith.
  if (length(unique(z$sd2019)) != 1)
    stop("cell '", lab, "' has more than one sd2019 in ", IN, call. = FALSE)
  list(label       = lab,
       q2019       = z$q2019,
       d           = z$d,
       g_star      = z$g_star,
       sd2019      = z$sd2019[1])
})

## Presets for the effect and participation controls, with their sources, so
## the page can show where each chip comes from.
strip <- function(recs, fields) lapply(recs, function(r) r[fields])
## Provenance is an MD5 of each source file rather than a run date, so
## rerunning the script on unchanged inputs writes a byte-identical file and
## git shows a change only when the data did.
srcs <- c(IN, attr(cfg, "path"))
payload <- list(
  sources        = lapply(srcs, function(f) list(path = f, md5 = unname(tools::md5sum(f)))),
  percentiles    = PS,
  cells          = cells,
  benchmarks     = strip(cfg_get(cfg, "benchmarks"),    c("id", "g", "label", "source")),
  participation  = strip(cfg_get(cfg, "participation"), c("id", "c", "label", "source")),
  treated_effect = cfg_get(cfg, "treated_effect")
)

dir.create(dirname(OUT), showWarnings = FALSE, recursive = TRUE)
## digits = NA writes full double precision, so the page and the test see
## exactly the values in the CSV.
json <- jsonlite::toJSON(payload, auto_unbox = TRUE, digits = NA, pretty = TRUE)
writeLines(c("// Generated by analysis/10-export-tool-data.R. Do not edit by hand.",
             paste0("globalThis.TOOL_DATA = ", json, ";")), OUT)
cat("wrote", OUT, "(", length(cells), "cells )\n")
